-- ============================================================
-- Self-register / admin-approve provisioning.
--
-- A user logging in via Auth0 (Google social or email+password)
-- has no local `users` row on first login — and a Google `sub`
-- (google-oauth2|…) does not even exist until that first login,
-- so the super admin cannot pre-paste it. Instead, the frontend
-- self-registers the caller into this pending queue on first login;
-- a SUPER_ADMIN then approves it (assigning a role), which creates
-- the real `users` row and clears the pending entry.
--
-- This table holds ONLY not-yet-approved registrations. It carries
-- no role — role is chosen at approval time on the `users` row.
--
-- Managed by Flyway. Never modify this file after deployment.
-- ============================================================

CREATE TABLE pending_users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth0_sub    VARCHAR(128) NOT NULL UNIQUE,
    email        VARCHAR(160),
    full_name    VARCHAR(100),
    requested_at TIMESTAMP    NOT NULL
);
